### ISSUE TITLE
Make witherable-0.5 release

### ISSUE THREAD

**Issue by phadej** [fumieval/witherable#102]
I made few major changes yesterday, from the changelog:

- `FilterableWithIndex` is a superclass of `WitherableWithIndex`.
- Remove deprecated `Data.Witherable` module. Use `Witherable` module.
- Relax `FilterableWithIndex` composition law so list-like instances are lawful.
- Add `drain :: f a -> f b` method (with default implementation `drain = mapMaybe (Const Nothing)`) to the `Filterable`.

And also removed `witherable-class` package from the repository, as it would also need a major version bump, so better to just forget about it now.

The `master` is now in a releasable state. But if someone have something extra in mind, please speak up. Let's make release sometime later this month.

**Comment by phadej** [comment]
ping @fumieval

**Comment by phadej** [comment]
ping @fumieval

**Comment by fumieval** [comment]
Sorry, I hadn't noticed this issue! Looks good to me

**Comment by fumieval** [comment]
Uploaded https://hackage.haskell.org/package/witherable-0.5

**Comment by phadej** [comment]
Thanks!
