### ISSUE TITLE
Possibly useful helper functions?

### ISSUE THREAD

**Issue by MichaelBurge** [fumieval/witherable#12]
Hello,

Thanks for writing this library!

I have a compiler where I debug errors by reducing the syntax tree to a minimal testcase that still exhibits the error. I plan to use Witherable to write generic reduction algorithms of this sort. While writing one, I had to write a few non-obvious functions and thought you'd be interested in seeing them, in case they suggest useful generalizations in your library.

minimize has at least a O(n^2) runtime: Since the global property may depend on complex interactions between multiple elements, it's only safe to remove a single element at a time.

```
import Data.List
import Data.Witherable as W

indexed :: Traversable t => t a -> t (Int, a)
indexed xs = snd $ mapAccumL (\i x -> (i+1, (i, x))) (-1) xs

-- A deleter of x is x together with a view of the Witherable with that element deleted.
deleters :: Witherable w => w a -> w (a, w a)
deleters xs = fmap (\(i, x) -> (x, fmap snd $ W.filter (\(j, _) -> i /= j) xs')) xs' where xs' = indexed xs

-- Repeatedly remove elements as long as a global property holds.
-- filter takes an elementwise property; this takes a property of the entire Witherable.
minimize :: Witherable w => (w a -> Bool) -> w a -> w a
minimize hasError xs = case find (\(_, xs') -> hasError xs') $ deleters xs of
  Nothing -> xs
  Just (_, xs') -> minimize hasError xs'

main = putStrLn $ show $ minimize (even . sum) [200,-50,1,39,7,50,60,90,100]
-- Prints [39,7], which is a minimal list where no single element can be removed while keeping the sum even.

```

**Comment by fumieval** [comment]
Hmm, It strikes me that `Witherable` is not a good fit for your usecase. Lists, `Seq`, and maps would have much better implementations of `deleters`, but `Witherable` isn't enough to express them.

**Comment by MichaelBurge** [comment]
I think you're probably right. A function to get all single-point reductions seems like the more important primitive for me, while `Witherable` emphasizes `catMaybes` for eliminating entire sets at once without wanting to focus on specific elements.

Thanks anyways for looking at it.
