### ISSUE TITLE
Add witherM method

### ISSUE THREAD

**Issue by treeowl** [fumieval/witherable#23]
Some `Witherable` types can't implement a particularly efficient `wither`, but *can* implement an efficient one with a `Monad m` constraint instead of an `Applicative` one. This is true of `Data.Vector.Vector`, for example. I think we should add a `witherM` method to support that.

**Comment by treeowl** [comment]
Hrmmm.... I see there's already a *function* by this name whose type includes `MaybeT` for reasons I cannot divine. There's really nothing `MaybeT`ish about the actual API. I propose that we *change the type* of `witherM` and also make it a `Witherable` method.

```haskell
class Traversable t => Witherable t where
  ...
  witherM :: Monad m => (a -> m (Maybe b)) -> t a -> m (t b)
#if MIN_VERSION_base(4,8,0)
  witherM = wither
#elif __GLASGOW_HASKELL__ >= 708
  witherM f = unwrapMonad . wither (coerce f)
#else
  witherM f = unwrapMonad . wither (WrapMonad . f)
#endif
```

What do you think, @fumieval? The alternative is to try to come up with some other name for the new method, but I don't much care for that idea.

**Comment by treeowl** [comment]
Sounds good then.

**Comment by fumieval** [comment]
Added in d31a8dadea3cdd502bb7a409063337401bbd0326
