### ISSUE TITLE
Filterable from Alternative and Monad?

### ISSUE THREAD

**Issue by josephcsible** [fumieval/witherable#31]
Currently, this package has `Filterable` instances for `[]`, `Maybe`, and a few other types that are instances of both `Alternative` and `Monad`. Would it be possible/beneficial to remove all of these individual instances, and replace them with a single instance like this?

```haskell
import Control.Applicative (empty)

instance (Monad t, Alternative t) => Filterable t where
  mapMaybe f x = x >>= maybe empty return . f
```

**Comment by fumieval** [comment]
I don't think defining an instance for _every_ type is a good idea; the typeclass is not even needed. That would disallow instances for Maps.

**Comment by josephcsible** [comment]
It's not really for *every* type. `Map` is neither an instance of `Monad` nor of `Traversable`, so this instance wouldn't apply to it, and it could thus keep its existing instance.

**Comment by fumieval** [comment]
But Map is an instance of Traversable. http://hackage.haskell.org/package/containers-0.6.0.1/docs/Data-Map-Lazy.html#t:Map

**Comment by josephcsible** [comment]
> The thing is: if you add such an instance, it would be an instance declaration for **every type**, not just ones that satisfy `Monad` and `Alternative`.

D'oh. I totally forgot that. Sorry for the noise.
