### ISSUE TITLE
Indexed variants

### ISSUE THREAD

**Issue by quasicomputational** [fumieval/witherable#40]
`mapMaybeWithIndex` and `traverseMaybeWithIndex` are two more potential spots for generalisation.

I think doing this properly would require depending on `lens` to get the `FunctorWithIndex` class - maybe it would make more sense to shunt it into a `witherable-indexed` package? That's how `semialign` and `semialign-indexed` are set up.

**Comment by quasicomputational** [comment]
Ah - there's actually already a `lens` dependency via `monoidal-containers`, so never mind about trying to be clever and avoid it.

**Comment by fumieval** [comment]
Well, I was actually thinking about reverting the change to introduce the lens dependency... I guess it's too late.

**Comment by quasicomputational** [comment]
Eh, this stuff could easily be put into `witherable-indexed`. But the `monoidal-containers` instances are handy!
