### ISSUE TITLE
Data.Set.Monad instance

### ISSUE THREAD

**Issue by deepfire-pusher** [fumieval/witherable#47]
`Data.Set.Monad` could also use an instance: http://hackage.haskell.org/package/set-monad-0.3.0.0/docs/Data-Set-Monad.html#t:Set

**Comment by fumieval** [comment]
In the future, I prefer having instances on where datatypes are defined (especially non-standard ones), not in this package.

**Comment by fumieval** [comment]
Closing as Wontfix
