### ISSUE TITLE
Harmonize Travis script with Cabal bounds

### ISSUE THREAD

**Issue by treeowl** [fumieval/witherable#52]
We seem to try to support GHC versions going back a long way, but we only test recent versions with Travis. We should either

1. Bump the `base` dependency version and remove compat code, or
2. Update the `Tested-With` field and regenerate the Travis script to make sure the compat code continues to work.

**Comment by treeowl** [comment]
For example, right now we have checks for `__GLASGOW_HASKELL__ >= 708`, but the package can't compile on pre-AMP GHC!

**Comment by treeowl** [comment]
I'd be happy to work on implementing either option once you decide which you prefer.

**Comment by fumieval** [comment]
The CPPs are probably no longer relevant... I don't plan to support old GHC so I'll remove those

**Comment by fumieval** [comment]
Mostly removed in ab020588b6257d3f302e850b9c6b622435e6b8b1 I think.

**Comment by phadej** [comment]
CI tests all supported GHCs now.
