### ISSUE TITLE
Unsplit package?

### ISSUE THREAD

**Issue by treeowl** [fumieval/witherable#54]
The package split seems to have led to orphans. What is gained at that terrible price?

**Comment by treeowl** [comment]
Wait, maybe I'm confused.

**Comment by fumieval** [comment]
Since #37, the direction of the package has become "define instances of everything in the ecosystem". The huge dependency will be (or already is) a problem, so I decided to split the package so that library authors can define instances with only `witherable-class` dependency.

**Comment by treeowl** [comment]
So are you looking to push the instances into other packages? That seems reasonable if you can get buy-in. But `containers` won't be able to do it unless `witherable` becomes a GHC boot package, so please consider an exception. Also, `Array` will need an exception for even nastier reasons.

**Comment by fumieval** [comment]
Right. I compromised with including containers, transformers, unordered-containers and vector.
