### ISSUE TITLE
Document a consequence of the laws

### ISSUE THREAD

**Issue by treeowl** [fumieval/witherable#58]
There's an intuitively obvious law that follows from the `Filterable` laws in a way I found less than obvious.

### Law

Suppose that `xs :: f a` and that for all `b :: Type` and all `f, g :: a -> b`, `fmap f xs = fmap g xs` (that is, `xs` does not actually "contain" any `a` values). Then for all `c :: Type` and all `h, i :: a -> Maybe c`, `mapMaybe h xs = mapMaybe i xs`. Letting `h` be `Just` leads to a nice corollary about `filter`.

### Proof

Suppose that for all `b :: Type` and all `f, g :: a -> b`, `fmap f xs = fmap g xs`.

Then by the preservation law, for all `f,g :: a -> b`,
`mapMaybe (Just . f) xs = mapMaybe (Just . g) xs`

Therefore, for all `c :: Type` and all `h, i :: a -> Maybe c`,

`mapMaybe id . mapMaybe (Just . h) $ xs = mapMaybe id . mapMaybe (Just . i) $ xs`

By the composition law,

`mapMaybe h xs = mapMaybe i xs`.

I imagine we can prove a similar theorem about `wither`.

**Comment by alexfmpe** [comment]
I imagine `mapMaybe h xs = mapMaybe i c` should be `mapMaybe h xs = mapMaybe i xs`

**Comment by treeowl** [comment]
> I assume `mapMaybe h xs = mapMaybe i c`
> should be `mapMaybe h xs = mapMaybe i xs`

Fixed.

**Comment by treeowl** [comment]
Indeed, it's possible to prove that this holds for `wither` as well, combining all three of the laws and using the fact that `Compose . fmap Identity` is an applicative transformation.

**Comment by treeowl** [comment]
Under the conditions described above, if `f, g :: a -> f (Maybe b)`, then `wither f xs = wither g xs`.

```haskell
wither (fmap Just . f) xs = traverse f xs = sequence (fmap f xs) = sequence (fmap g xs) = traverse g xs = wither (fmap Just . g) xs
```

So

```haskell
Compose . fmap (wither Identity) . wither (fmap Just . f) $ xs =
Compose . fmap (wither Identity) . wither (fmap Just . g) $ xs
```

Applying the composition law,

```haskell
wither (Compose . fmap (wither Identity) . fmap Just . f) xs =
wither (Compose . fmap (wither Identity) . fmap Just . g) xs

-- second functor law

wither (Compose . fmap (wither Identity . Just) . f) xs =
wither (Compose . fmap (wither Identity . Just) . g) xs

-- inline wither for Maybe

wither (Compose . fmap Identity . f) xs =
wither (Compose . fmap Identity . g) xs
```

Since `Compose . fmap Identity` is an applicative transformation,

```haskell
Compose . fmap Identity $ wither f xs =
Compose . fmap Identity $ wither g xs
```

Since `Compose . fmap Identity` is injective, `wither f xs = wither g xs`.

Whew!
