### ISSUE TITLE
witherable-class: packaging issues

### ISSUE THREAD

**Issue by endgame** [fumieval/witherable#65]
I noticed a couple of issues with the `witherable-class` packaging:

1. There are no bounds on its dependencies.
2. The `CHANGELOG.md` file describes a version 0.1.0.0 which does not exist, and has no release date.

**Comment by fumieval** [comment]
Fixed in 453175003

**Comment by endgame** [comment]
Awesome, thanks. I don't know if you prefer to close issues on shipping to hackage, or as soon as they hit master, so I'll leave that bit to you.
