### ISSUE TITLE
Classes for nonempty data types?

### ISSUE THREAD

**Issue by jhgarner** [fumieval/witherable#69]
I've found it useful to have `mapMaybe1 :: (a -> Maybe b) -> f a -> Maybe (f a)` for things like nonempty lists. Defining new typeclasses called `Filterable1` and `Witherable1` using some of the classes from https://hackage.haskell.org/package/semigroupoids seems like it would be pretty straightforward. Would this addition be something you would consider adding? If so, I can open up a pull request that tries to add these classes and instances.

**Comment by fumieval** [comment]
The idea sounds good. However, the amount of dependencies `semigroupoids` drags is a bit worrisome (we've just managed to get rid of the dependency to lens, thanks to indexed-traversable).

I'm definitely willing to include Filterable1/Witherable1 once Foldable1 is added to base.

**Comment by phadej** [comment]
> Having a typeclass that converts NonEmpty into regular data leaves us one question: what's wrong with doing the conversion first and use Filterable / Witherable methods?

Good question indeed!

**Comment by fumieval** [comment]
We concluded that this should be solved by converting non-empty data to the emptiable counterpart.

Closing as it's out of scope of this library.
