### ISSUE TITLE
use indexed-traversable rather than lens?

### ISSUE THREAD

**Issue by cartazio** [fumieval/witherable#70]
cc @phadej et al (maybe also ryan?)

**Comment by phadej** [comment]
`monoidal-containers` depends on `lens`, so one cannot trim dependencies here. Sadly.

**Comment by cartazio** [comment]
hrmm, wouldn't it work if the WitherWithIndex classes were moved into https://github.com/fumieval/witherable/tree/master/witherable-class (witherable-class) package?

**Comment by phadej** [comment]
That could work.

**Comment by fumieval** [comment]
Sounds good to me. Also I was planning to remove the dependency on monoidal-containers

**Comment by phadej** [comment]
It looks to me that if `monoidal-containers` is dropped, and `WithIndex` classes are moved to `witherable-class`, there isn't much left in `witherable`. Lensy optics (and some synonyms?). Is this correct, or do I miss something?

**Comment by fumieval** [comment]
The motivation for `witherable-class` was to avoid the lens dependency. At this point we could merge witherable-class into witherable

**Comment by fumieval** [comment]
Done and uploaded [witherable-0.4](https://hackage.haskell.org/package/witherable-0.4) and [witherable-class-0.0.1](https://hackage.haskell.org/package/witherable-class-0.0.1)

**Comment by phadej** [comment]
@fumieval thanks. `witherable` is now nicely tiny-dep-footprint package! I hope it will stay this way :)
