### ISSUE TITLE
Why does witherable not depend on witherable-class?

### ISSUE THREAD

**Issue by blamario** [fumieval/witherable#82]
I prefer having my packages depend on `witherable-class` because I don't care for the extra dependencies of `witherable`. Sadly the former appears to be deprecated, presumably to avoid splitting the exosystem. Why can't `witherable` import the classes from `witherable-class` and just add the extra (orphan) instances?

**Comment by fumieval** [comment]
The motivation for having witherable-class was `witherable` (unintentionally) depending on `lens`. But the dependency is no more, so I moved the class definition from `witherable-class` to `witherable`.

Is any of witherable's dependencies causing a problem?

**Comment by blamario** [comment]
Sorry about the delayed response.

I'm not sure about the order of events, but some time ago I decided to depend on `witherable-class` instead of `witherable` because of its lighter dependencies. That may have been because of `lens`, I don't remember. But now I see that `witherable-class` is deprecated, which means I must switch to `witherable` after all. Its current dependencies are not too heavy.

My question still stands though: why can't witherable import the classes from witherable-class and just add more instances?

**Comment by fumieval** [comment]
In order to avoid confusion related to orphan instances. There have been objections when I split the package to `witherable-class`. I'm not going to revert the decision.

**Comment by blamario** [comment]
Ok, thanks for the clarification.
